Add new alchemix domains
connext/chaindata pull request #186
Opened 2024-07-26 21:26 UTC by just-a-node

2024-07-26 22:51 UTC, preethamr submitted a review, later dismissed

2024-07-29 16:16 UTC, LayneHaber submitted a review, later dismissed

2024-07-29 16:28 UTC, LayneHaber requested changes
shouldn't touch the everlcear files?

2024-07-29 16:34 UTC, just-a-node commented
Diff shows `everclear.testnet.staging.json` changes but was rebased against `main`.

2024-07-29 16:59 UTC, closed without merging