feat: testnet staging contracts
connext/chaindata pull request #219
Opened 2024-09-10 07:49 UTC by just-a-node

2024-09-12 21:07 UTC, LayneHaber requested changes
was arb-sepolia not redeployed on staging?

2024-09-12 21:07 UTC, LayneHaber commented on everclear.testnet.staging.json
> +        "gateway": "0x645219a36CB7254Ea367B645ED3eA512e14BBbEA"
mismatch from the original repository, `SpokeGateway` and `EverclearSpoke` match this address: `0xda058E1bD948457EB166D304a2680Fe1c813AC21` in the artifacts

2024-09-12 21:26 UTC, just-a-node commented on everclear.testnet.staging.json
>        "gasLimit": 120000000,
Was deployed with 70m

2024-09-13 00:46 UTC, LayneHaber approved these changes

2024-09-16 17:05 UTC, prathmeshkhandelwal1 approved these changes

2024-09-16 17:06 UTC, merged